sites:
  - host: s7.hostlocal.com
    comment: Linode
    ips:
      - "173.255.196.65"

  - mx: code-maven.com
    ips:
      - mx1.forwardemail.net.
      - mx2.forwardemail.net.

  - txt: code-maven.com
    expected:
      - '"v=spf1 a mx include:spf.forwardemail.net include:hostlocal.com  include:_spf.google.com -all"'
      - '"forward-email-site-verification=3gnVe9O6Sk"'

  - host: hostlocal.com
    ips: github

  - host: www.hostlocal.com
    ips: github

  - url: https://hostlocal.com/
    enabled: true
    status_code: 200
    html_contains: "<title>Host Local Training courses for Rust and Python</title>"

  - url: http://hostlocal.com/
    status_code: 301
    headers:
      Location: https://hostlocal.com/

  - url: http://www.hostlocal.com/
    status_code: 301
    headers:
      Location: https://hostlocal.com/

  - url: http://s7.hostlocal.com/
    status_code: 301
    headers:
      Location: https://code-maven.com/

  - url: https://mail.hostlocal.com/mailman/listinfo
    comment: "requests complains about SSL certificate"
    enabled: false
    status_code: 200
    html_contains: "<TITLE>mail.hostlocal.com Mailing Lists</TITLE>"

  - url: https://mail.hostlocal.com/
    comment: "requests complains about SSL certificate"
    enabled: false
    status_code: 301
    headers:
      Location: https://mail.hostlocal.com/mailman/listinfo

