sites:
  - host: pti.co.il
    ips:
      - 173.255.196.65

  - host: www.pti.co.il
    ips:
      - 173.255.196.65

  - url: http://pti.co.il/
    status_code: 301
    headers:
      Location: https://pti.szabgab.com/

  - url: http://www.pti.co.il/
    status_code: 301
    headers:
      Location: https://pti.szabgab.com/


